spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
  profiles:
    active: dev

comment.avatar: /images/xiongmao.jpg